---
 - name: Collect all necessary facts and set them if needed
   include_tasks: set_facts.yml
 - name: Install all VMs
   include_tasks: createVMcfg.yml
   with_items: "{{ xen_vman_vms }}"
   when: vm.hypervisor == inventory_hostname and vm.isrunning == false
   loop_control:
    loop_var: vm