---
 - name: clear lvm on source
   include_tasks: clear_lvm.yml
   with_items: "{{ xen_vman_vms }}"
   when: vm.hypervisor == inventory_hostname
   loop_control:
    loop_var: vm
 - name: clear lvm on target
   include_tasks: clear_lvm.yml
   with_items: "{{ xen_vman_vms }}"
   when: vm.target == inventory_hostname
   loop_control:
    loop_var: vm

